#![warn(missing_docs)]

//! # GamesmanNova Interfaces Library
//! 
//! `interfaces` provides all the available ways to interact with GamesmanNova.
//! 
//! #### Authorship
//! 
//! - Max Fierro, 4/6/2023 (maxfierro@berkeley.edu)

/// All terminal-related modes of interaction, including a command line
/// interface (CLI) and a terminal user interface (TUI).
pub mod terminal;

/// All non-terminal related graphical means of user interaction.
pub mod graphical;

/// All networked means of interaction, including a daemon process for serving
/// the databases generated by the solvers in `core`.
pub mod networked;
